/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cab943f9-f5c2-4736-83ef-ece9654b6c63",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Xk7xtR3G0",
    "aws_user_pools_web_client_id": "5hsi0qig7oonte8e5eftda1c0t",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "team",
            "endpoint": "https://k8xhyblzk2.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
